### ISSUE TITLE
不知道怎么过审的，这个插件完全不符合审核规范

### ISSUE THREAD

**Issue by tsztodd** [laozhoubuluo/discuz_ranklistlimit#2]
应当尽量少用common嵌入点，完全可以不用common的
使用脚本嵌入点的自定义嵌入点

**Comment by laozhoubuluo** [comment]
之前测试自定义嵌入点是没法勾住这个位置的，https://www.dismall.com/thread-210-1-1.html 这个帖子也指出了这个问题。
不过也有可能是我测试不完善，如果您能找到合适的钩子可以 PR 一下或者告诉我名字，我这边修改后发新版。
